apiVersion: v2
name: fake-service
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
# Tag from https://hub.docker.com/r/nicholasjackson/fake-service/tags
appVersion: "v0.24.2"
